name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Install TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.34.0/tinygo_0.34.0_amd64.deb
          sudo dpkg -i tinygo_0.34.0_amd64.deb
          export PATH=$PATH:/usr/local/bin
      
      - name: Build Plugin
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          make build VERSION=$VERSION
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            
            dist/umbeluzi-bar*.wasm
            